export {Header} from "./Header"
export {Newslatter} from "./Newslatter"
export {Testimonial} from "./Testimonial"
export {HeroSlider} from "./Home/HeroSlider"
export { HeroAbout} from "./About/HeroAbout"
export {Feature} from "./About/Feature"
export {Investors} from "./About/Investors"
export {Visibility} from "./safety/Visibility"
export {Training} from "./safety/Training"
export {Market} from "./automotive/Market"
export {Cases} from "./automotive/Cases"